// AUTO-GENERATED by emit-sdk — do not edit.
// Source: plugin.json `action_types`. Run: just gen-plugins

package main

import "github.com/branchkit/plugin-sdk-go"

// DeskSwitchParams is the params shape for action "windows.desk_switch (Switch Desktop)".
type DeskSwitchParams struct {
	Space string `json:"space"`
}

// HandleDeskSwitch registers a typed handler for action "windows.desk_switch (Switch Desktop)".
func HandleDeskSwitch(p *branchkit.Plugin, fn func(DeskSwitchParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "windows.desk_switch", fn)
}

// MoveToSpaceParams is the params shape for action "windows.move_to_space (Move Window to Space)".
type MoveToSpaceParams struct {
	Space    string  `json:"space"`
	Stay     *bool   `json:"stay,omitempty"`
	WindowID *string `json:"window_id,omitempty"`
}

// HandleMoveToSpace registers a typed handler for action "windows.move_to_space (Move Window to Space)".
func HandleMoveToSpace(p *branchkit.Plugin, fn func(MoveToSpaceParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "windows.move_to_space", fn)
}

// SnapPosition is a generated enum type.
type SnapPosition string

const (
	SnapPositionLeft     SnapPosition = "left"
	SnapPositionRight    SnapPosition = "right"
	SnapPositionMaximize SnapPosition = "maximize"
	SnapPositionCenter   SnapPosition = "center"
	SnapPositionNext     SnapPosition = "next"
	SnapPositionPrev     SnapPosition = "prev"
)

// SnapParams is the params shape for action "windows.snap (Snap Window)".
type SnapParams struct {
	Position *SnapPosition `json:"position,omitempty"`
}

// HandleSnap registers a typed handler for action "windows.snap (Snap Window)".
func HandleSnap(p *branchkit.Plugin, fn func(SnapParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "windows.snap", fn)
}
