// AUTO-GENERATED by emit-sdk — do not edit.
// Source: plugin.json `action_types`. Run: just gen-plugins

package main

// DeskSwitchParams is the params shape for action "windows.desk_switch (Switch Desktop)".
type DeskSwitchParams struct {
	Space string `json:"space"`
}

// MoveToSpaceParams is the params shape for action "windows.move_to_space (Move Window to Space)".
type MoveToSpaceParams struct {
	Space string `json:"space"`
	Stay *bool `json:"stay,omitempty"`
	WindowID *string `json:"window_id,omitempty"`
}

// SnapPosition is a generated enum type.
type SnapPosition string

const (
	SnapPositionLeft SnapPosition = "left"
	SnapPositionRight SnapPosition = "right"
	SnapPositionMaximize SnapPosition = "maximize"
	SnapPositionCenter SnapPosition = "center"
	SnapPositionNext SnapPosition = "next"
	SnapPositionPrev SnapPosition = "prev"
)

// SnapParams is the params shape for action "windows.snap (Snap Window)".
type SnapParams struct {
	Position *SnapPosition `json:"position,omitempty"`
}

