// AUTO-GENERATED by emit-sdk — do not edit.
// Source: plugin.json `action_types`. Run: just gen-plugins

package main

// MoveToSpaceParams is the params shape for action "windows.move_to_space (Move Window to Space)".
type MoveToSpaceParams struct {
	Space string `json:"space"`
}

// SnapPosition is a generated enum type.
type SnapPosition string

const (
	SnapPositionLeft SnapPosition = "left"
	SnapPositionRight SnapPosition = "right"
	SnapPositionMaximize SnapPosition = "maximize"
	SnapPositionCenter SnapPosition = "center"
	SnapPositionNext SnapPosition = "next"
	SnapPositionPrev SnapPosition = "prev"
)

// SnapParams is the params shape for action "windows.snap (Snap Window)".
type SnapParams struct {
	Position *SnapPosition `json:"position,omitempty"`
}

// TabToSpaceParams is the params shape for action "windows.tab_to_space (Move Browser Tab to Space)".
type TabToSpaceParams struct {
	Space string `json:"space"`
}

// TabToWindowParams is the params shape for action "windows.tab_to_window (Move Browser Tab to Window)".
type TabToWindowParams struct {
	Index string `json:"index"`
}

